language: java
sudo: false
install: true

jdk:
  - oraclejdk7

env:
  - JOB=H2
  - JOB=POSTGRES
  - JOB=MYSQL
#  - JOB=WEB
#  - JOB=ITS_ISSUE
#  - JOB=ITS_QUALITYGATE
#  - JOB=ITS_UPDATECENTER
#  - JOB=ITS_TESTING
#  - JOB=ITS_MEASURE
#  - JOB=ITS_UI
#  - JOB=ITS_PLUGINS

matrix:
  fast_finish: true

script:
  - ./travis.sh

cache:
  directories:
    - '$HOME/.m2/repository'
    - 'server/sonar-web/node'
    - 'server/sonar-web/node_modules'

before_cache:
  - 'rm -rf $HOME/.m2/repository/org/codehaus/sonar'
  - 'rm -f server/sonar-web/npm-debug.log'

notifications:
  email: false
